export const iconSize = {
  xs: 16,
  sm: 18,
  md: 20,
  lg: 24,
  xl: 28,
};

export const ICONS = {
  home: { filled: 'home', outline: 'home-outline' },
  prayer: { filled: 'moon', outline: 'moon-outline' },
  quran: { filled: 'book', outline: 'book-outline' },
  dhikr: { filled: 'heart', outline: 'heart-outline' },
  more: { filled: 'grid', outline: 'grid-outline' },
  dua: { filled: 'hand-left', outline: 'hand-left-outline' },
  spouse: { filled: 'heart-circle', outline: 'heart-circle-outline' },
  settings: { filled: 'settings', outline: 'settings-outline' },
  profile: { filled: 'person', outline: 'person-outline' },
  notifications: { filled: 'notifications', outline: 'notifications-outline' },
  privacy: { filled: 'shield-checkmark', outline: 'shield-checkmark-outline' },
  location: { filled: 'location', outline: 'location-outline' },
  zakat: { filled: 'wallet', outline: 'wallet-outline' },
  fasting: { filled: 'restaurant', outline: 'restaurant-outline' },
  tahajjud: { filled: 'moon', outline: 'moon-outline' },
  hajj: { filled: 'airplane', outline: 'airplane-outline' },
  calendar: { filled: 'calendar', outline: 'calendar-outline' },
  search: 'search',
  checkmark: { filled: 'checkmark-circle', outline: 'checkmark-circle-outline' },
  close: { filled: 'close-circle', outline: 'close-circle-outline' },
  add: { filled: 'add-circle', outline: 'add-circle-outline' },
  delete: { filled: 'trash', outline: 'trash-outline' },
  share: { filled: 'share', outline: 'share-outline' },
  copy: { filled: 'copy', outline: 'copy-outline' },
  chevron: 'chevron-forward',
  refresh: 'refresh',
  stats: 'stats-chart',
  info: 'information-circle-outline',
  link: 'link',
  person: { filled: 'person-circle', outline: 'person-circle-outline' },
  time: 'time-outline',
  check: 'checkmark',
  flame: 'flame',
  trophy: 'trophy-outline',
  play: 'play',
  star: 'star',
};
